version: '3.5'
services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./docker/front.Dockerfile
    ports: 
      - 8080:8080
    volumes:
      - ./client:/code
      - node_modules:/code/node_modules
    command: bash -c "yarn install && yarn dev"

  api:
    container_name: api
    build: 
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - ./api:/code
    command: bash -c "bundle install && rails server -p 3000 -b '0.0.0.0'"

  # db:

volumes: 
  node_modules: